name: 'Publish GitHub pages'
description: 'Publish static site to orphan GitHub pages branch'
inputs:
  src_dir:
    description: 'Source dir with static site build'
    required: false
    default: './build'
  dest_dir:
    description: 'Dir to publish site content'
    required: false
    default: '.'
  branch:
    description: 'GitHub pages branch'
    required: false
    default: 'gh-pages'
  deploy_private_key:
    description: 'Deploy private SSH key secret'
    required: true
  author_name:
    description: 'Commit author name'
    required: false
  author_email:
    description: 'Commit author email'
    required: false
  important_files:
    description: 'Files outside the build that should be in the result'
    required: false
  debug:
    description: 'Log debug messages'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
